- name: "install and configure basic tools"
  hosts: "k8sCommonOnUbuntu"
  become: yes
  tasks:
  - name: install docker.io
    apt:
      name: docker.io
      update_cache: yes
      state: present
  - name: install apt-transport-https
    apt:
      name: apt-transport-https
      update_cache: yes
      state: present
  - name: install curl
    apt:
      name: curl
      update_cache: yes
      state: present
  - name: install wget
    apt:
      name: wget
      update_cache: yes
      state: present

  - name: install kubelet
    apt:
      name: kubelet
      update_cache: yes
      state: present
  - name: Hold kubelet
    dpkg_selections:
      name: kubelet
      selection: hold

  - name: install kubeadm
    apt:
      name: kubeadm
      update_cache: yes
      state: present
  - name: Hold kubeadm
    dpkg_selections:
      name: kubeadm
      selection: hold

  - name: install kubectl
    apt:
      name: kubectl
      update_cache: yes
      state: present
  - name: Hold kubectl
    dpkg_selections:
      name: kubectl
      selection: hold
       