- name: "setup k8s"
  hosts: "k8sCommonOnUbuntu"
  become: true
  tasks:
  - name: "add overlay"
    modprobe:
      name: overlay
      state: present
  - name: "add br_netfilter"
    modprobe:
      name: br_netfilter
      state: present

  - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

  - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

  - name: ensure net.ipv4.ip_forward is set to 1
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present

  # - sysctl:
  #     reload: yes
     
  # - name: "create docker daemon json"
  #   copy:
  #     content: "{"exec-opts":["native.cgroupdriver=systemd"],"log-driver":"json-file","log-opts":{"max-size":"100m"},"storage-driver":"overlay2"}"
  #     dest: "/etc/sysctl.d/kubernetes.conf"
  #     create: yes

  - name: force systemd to reread configs
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: restart docker
    ansible.builtin.systemd:
      state: restarted
      name: docker

  - name: enable docker
    ansible.builtin.systemd:
      name: docker
      enabled: yes