- name: "setup k8s master"
  hosts: "k8master"
  become: true
  tasks:
    - name: pull kube images
      shell: kubeadm config images pull

    - name: initialize the cluster
      shell: kubeadm init --control-plane-endpoint=blue.pkvnw >> cluster_initialized.txt
      args:
        chdir: /home/pkv
        creates: cluster_initialized.txt

    - name: create .kube directory
      file:
        path: /home/pkv/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/pkv/.kube/config
        remote_src: yes

    - name: Change kubeconfig file permission
      file:
        path: /home/pkv/.kube/config 
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"

    - name: install Pod network
      become: false
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml >> pod_network_setup.txt
      args:
        chdir: /home/pkv
        creates: pod_network_setup.txt