- name: "get master token" 
  hosts: k8master
  become: yes
  tasks:
    - name: get join command
      # shell: kubeadm token create --print-join-command
      command: "kubeadm token create --kubeconfig /etc/kubernetes/admin.conf --print-join-command"

      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: k8worker
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars[groups['k8master'] | last].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt