- name: "cleanup"
  hosts: "k8sCommonOnUbuntu"
  become: true
  tasks:
  - name: Reset all IPv4 iptables rules in all tables and allow all traffic
    shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

  - name: "Check if kubeadm is installed"    
    package_facts:
      manager: auto

  - name: kubeadm reset
    shell: kubeadm reset --force
    when: "'kubeadm' in ansible_facts.packages"

  - name: disable docker
    ansible.builtin.systemd:
      name: docker  
      enabled: no
    when: "'docker' in ansible_facts.packages"

  - name: stop docker
    ansible.builtin.systemd:
      name: docker  
      state: stopped 
    when: "'docker' in ansible_facts.packages"

  - name: unhold packages
    shell: apt-mark unhold kubeadm kubectl kubelet kubernetes-cni  kube* docker-ce  docker-ce-cli  ontainerd.io resolvconf

  - name: Remove k8s packages
    apt:
      pkg:
        - kubeadm
        - kubectl
        - kubelet
        - kubernetes-cni 
        - kube*
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - resolvconf
      state: absent
      purge: yes

  - name: Clean unwanted olderstuff
    apt:
      autoremove: yes
      purge: yes

  - name: delete k8s and docker files and directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /home/pkv/.kube/config
      - /etc/kubernetes/admin.conf
      - ~/.kube
      - /etc/docker/daemon.json
      - /etc/systemd/system/docker.service.d
      - /var/lib/docker
      - /etc/sysctl.d/kubernetes.conf

  - name: Remove docker route
    shell: ip route del 10.10.0.0 dev docker0
